class AWSFSBP_1_0_0:
    def __init__(self) -> None:
        self.standard_list = ["AccountComplianceChecker().account_one()",
        "ACMComplianceChecker().acm_one()",
        "ACMComplianceChecker().acm_two()",
        "APIGatewayComplianceChecker().apigateway_one()",
        "APIGatewayComplianceChecker().apigateway_two()",
        "APIGatewayComplianceChecker().apigateway_three()",
        "APIGatewayComplianceChecker().apigateway_four()",
        "APIGatewayComplianceChecker().apigateway_five()",
        "APIGatewayComplianceChecker().apigateway_eight()",
        "APIGatewayComplianceChecker().apigateway_nine()",
        "AppSyncComplianceChecker().appsync_two()",
        "AppSyncComplianceChecker().appsync_five()",
        "AutoScalingComplianceChecker().autoscaling_two()",
        "AutoScalingComplianceChecker().autoscaling_three()",
        "AutoScalingComplianceChecker().autoscaling_five()",
        "AutoScalingComplianceChecker().autoscaling_six()",
        "AutoScalingComplianceChecker().autoscaling_nine()",
        "BackupComplianceChecker().backup_one()",
        "CloudFrontComplianceChecker().cloudfront_one()",
        "CloudFrontComplianceChecker().cloudfront_three()",
        "CloudFrontComplianceChecker().cloudfront_four()",
        "CloudFrontComplianceChecker().cloudfront_five()",
        "CloudFrontComplianceChecker().cloudfront_six()",
        "CloudFrontComplianceChecker().cloudfront_seven()",
        "CloudFrontComplianceChecker().cloudfront_eight()",
        "CloudFrontComplianceChecker().cloudfront_nine()",
        "CloudFrontComplianceChecker().cloudfront_ten()",
        "CloudFrontComplianceChecker().cloudfront_twelve()",
        "CloudFrontComplianceChecker().cloudfront_thirteen()",
        "CloudTrailComplianceChecker().cloudtrail_one()",
        "CloudTrailComplianceChecker().cloudtrail_two()",
        "CloudTrailComplianceChecker().cloudtrail_four()",
        "CloudTrailComplianceChecker().cloudtrail_five()",
        "CodeBuildComplianceChecker().codebuild_one()",
        "CodeBuildComplianceChecker().codebuild_two()",
        "CodeBuildComplianceChecker().codebuild_three()",
        "CodeBuildComplianceChecker().codebuild_four()",
        "ConfigComplianceChecker().config_one()",
        "DMSComplianceChecker().dms_one()",
        "DMSComplianceChecker().dms_six()",
        "DMSComplianceChecker().dms_seven()",
        "DMSComplianceChecker().dms_eight()",
        "DMSComplianceChecker().dms_nine()",
        "DocumentDBComplianceChecker().docdb_one()",
        "DocumentDBComplianceChecker().docdb_two()",
        "DocumentDBComplianceChecker().docdb_three()",
        "DocumentDBComplianceChecker().docdb_four()",
        "DocumentDBComplianceChecker().docdb_five()",
        "DynamoDBComplianceChecker().dynamodb_one()",
        "DynamoDBComplianceChecker().dynamodb_two()",
        "DynamoDBComplianceChecker().dynamodb_three()",
        "DynamoDBComplianceChecker().dynamodb_six()",
        "EC2ComplianceChecker().ec2_one()",
        "EC2ComplianceChecker().ec2_two()",
        "EC2ComplianceChecker().ec2_three()",
        "EC2ComplianceChecker().ec2_four()",
        "EC2ComplianceChecker().ec2_six()",
        "EC2ComplianceChecker().ec2_seven()",
        "EC2ComplianceChecker().ec2_eight()",
        "EC2ComplianceChecker().ec2_nine()",
        "EC2ComplianceChecker().ec2_ten()",
        "EC2ComplianceChecker().ec2_fifteen()",
        "EC2ComplianceChecker().ec2_sixteen()",
        "EC2ComplianceChecker().ec2_seventeen()",
        "EC2ComplianceChecker().ec2_eighteen()",
        "EC2ComplianceChecker().ec2_nineteen()",
        "EC2ComplianceChecker().ec2_twenty()",
        "EC2ComplianceChecker().ec2_twentyone()",
        "EC2ComplianceChecker().ec2_twentythree()",
        "EC2ComplianceChecker().ec2_twentyfour()",
        "EC2ComplianceChecker().ec2_twentyfive()",
        "EC2ComplianceChecker().ec2_fiftyone()",
        "ECRComplianceChecker().ecr_one()",
        "ECRComplianceChecker().ecr_two()",
        "ECRComplianceChecker().ecr_three()",
        "ECSComplianceChecker().ecs_one()",
        "ECSComplianceChecker().ecs_two()",
        "ECSComplianceChecker().ecs_three()",
        "ECSComplianceChecker().ecs_four()",
        "ECSComplianceChecker().ecs_five()",
        "ECSComplianceChecker().ecs_eight()",
        "ECSComplianceChecker().ecs_nine()",
        "ECSComplianceChecker().ecs_ten()",
        "ECSComplianceChecker().ecs_twelve()",
        "EFSComplianceChecker().efs_one()",
        "EFSComplianceChecker().efs_two()",
        "EFSComplianceChecker().efs_three()",
        "EFSComplianceChecker().efs_four()",
        "EKSComplianceChecker().eks_one()",
        "EKSComplianceChecker().eks_two()",
        "EKSComplianceChecker().eks_eight()",
        "ElastiCacheComplianceChecker().elasticache_one()",
        "ElastiCacheComplianceChecker().elasticache_two()",
        "ElastiCacheComplianceChecker().elasticache_three()",
        "ElastiCacheComplianceChecker().elasticache_four()",
        "ElastiCacheComplianceChecker().elasticache_five()",
        "ElastiCacheComplianceChecker().elasticache_six()",
        "ElastiCacheComplianceChecker().elasticache_seven()",
        "ElasticBeanstalkComplianceChecker().elasticbeanstalk_one()",
        "ElasticBeanstalkComplianceChecker().elasticbeanstalk_two()",
        "ElasticBeanstalkComplianceChecker().elasticbeanstalk_three()",
        "ELBComplianceChecker().elb_one()",
        "ELBComplianceChecker().elb_two()",
        "ELBComplianceChecker().elb_three()",
        "ELBComplianceChecker().elb_four()",
        "ELBComplianceChecker().elb_five()",
        "ELBComplianceChecker().elb_seven()",
        "ELBComplianceChecker().elb_eight()",
        "ELBComplianceChecker().elb_nine()",
        "ELBComplianceChecker().elb_ten()",
        "ELBComplianceChecker().elb_twelve()",
        "ELBComplianceChecker().elb_thirteen()",
        "ELBComplianceChecker().elb_fourteen()",
        "EMRComplianceChecker().emr_one()",
        "EMRComplianceChecker().emr_two()"]

class CISAWSFundationsBenchmark_1_2_0:
    def __init__(self) -> None:
        self.standard_list = ["CloudTrailComplianceChecker().cloudtrail_one()",
        "CloudTrailComplianceChecker().cloudtrail_two()",
        "CloudTrailComplianceChecker().cloudtrail_four()",
        "CloudTrailComplianceChecker().cloudtrail_five()",
        "CloudTrailComplianceChecker().cloudtrail_six()",
        "CloudTrailComplianceChecker().cloudtrail_seven()",
        "CloudWatchComplianceChecker().cloudwatch_one()",
        "CloudWatchComplianceChecker().cloudwatch_two()",
        "CloudWatchComplianceChecker().cloudwatch_three()",
        "CloudWatchComplianceChecker().cloudwatch_four()",
        "CloudWatchComplianceChecker().cloudwatch_five()",
        "CloudWatchComplianceChecker().cloudwatch_six()",
        "CloudWatchComplianceChecker().cloudwatch_seven()",
        "CloudWatchComplianceChecker().cloudwatch_eight()",
        "CloudWatchComplianceChecker().cloudwatch_nine()",
        "CloudWatchComplianceChecker().cloudwatch_ten()",
        "CloudWatchComplianceChecker().cloudwatch_eleven()",
        "CloudWatchComplianceChecker().cloudwatch_twelve()",
        "CloudWatchComplianceChecker().cloudwatch_thirteen()",
        "CloudWatchComplianceChecker().cloudwatch_fourteen()",
        "ConfigComplianceChecker().config_one()",
        "EC2ComplianceChecker().ec2_two()",
        "EC2ComplianceChecker().ec2_six()",
        "EC2ComplianceChecker().ec2_thirteen()",
        "EC2ComplianceChecker().ec2_fourteen()",
        "test_CISAWSFundationsBenchmark_1_2_0"]

class CISAWSFundationsBenchmark_1_4_0:
    def __init__(self) -> None:
        self.standard_list = ["CloudTrailComplianceChecker().cloudtrail_one()",
        "CloudTrailComplianceChecker().cloudtrail_two()",
        "CloudTrailComplianceChecker().cloudtrail_four()",
        "CloudTrailComplianceChecker().cloudtrail_five()",
        "CloudTrailComplianceChecker().cloudtrail_six()",
        "CloudTrailComplianceChecker().cloudtrail_seven()",
        "CloudWatchComplianceChecker().cloudwatch_one()",
        "CloudWatchComplianceChecker().cloudwatch_four()",
        "CloudWatchComplianceChecker().cloudwatch_five()",
        "CloudWatchComplianceChecker().cloudwatch_six()",
        "CloudWatchComplianceChecker().cloudwatch_seven()",
        "CloudWatchComplianceChecker().cloudwatch_eight()",
        "CloudWatchComplianceChecker().cloudwatch_nine()",
        "CloudWatchComplianceChecker().cloudwatch_ten()",
        "CloudWatchComplianceChecker().cloudwatch_eleven()",
        "CloudWatchComplianceChecker().cloudwatch_twelve()",
        "CloudWatchComplianceChecker().cloudwatch_thirteen()",
        "CloudWatchComplianceChecker().cloudwatch_fourteen()",
        "ConfigComplianceChecker().config_one()",
        "EC2ComplianceChecker().ec2_two()",
        "EC2ComplianceChecker().ec2_six()",
        "EC2ComplianceChecker().ec2_seven()",
        "EC2ComplianceChecker().ec2_twentyone()",
        "test_CISAWSFundationsBenchmark_1_4_0"]

class NISTSP_800_53_Rev_5:
    def __init__(self) -> None:
        self.standard_list = ["AccountComplianceChecker().account_one()",
        "AccountComplianceChecker().account_two()",
        "ACMComplianceChecker().acm_one()",
        "APIGatewayComplianceChecker().apigateway_one()",
        "APIGatewayComplianceChecker().apigateway_two()",
        "APIGatewayComplianceChecker().apigateway_three()",
        "APIGatewayComplianceChecker().apigateway_four()",
        "APIGatewayComplianceChecker().apigateway_five()",
        "APIGatewayComplianceChecker().apigateway_eight()",
        "APIGatewayComplianceChecker().apigateway_nine()",
        "AppSyncComplianceChecker().appsync_five()"]

class PCI_DSS:
    def __init__(self) -> None:
        self.standard_list = ["AutoScalingComplianceChecker().autoscaling_one()",
        "CloudTrailComplianceChecker().cloudtrail_two()",
        "CloudTrailComplianceChecker().cloudtrail_two()",
        "CloudTrailComplianceChecker().cloudtrail_three()",
        "CloudTrailComplianceChecker().cloudtrail_four()",
        "CloudTrailComplianceChecker().cloudtrail_five()",
        "CloudWatchComplianceChecker().cloudwatch_one()",
        "CodeBuildComplianceChecker().codebuild_one()",
        "CodeBuildComplianceChecker().codebuild_two()",
        "ConfigComplianceChecker().config_one()",
        "DMSComplianceChecker().dms_one()",
        "EC2ComplianceChecker().ec2_one()",
        "EC2ComplianceChecker().ec2_two()",
        "EC2ComplianceChecker().ec2_six()",
        "EC2ComplianceChecker().ec2_twelve()",
        "EC2ComplianceChecker().ec2_thirteen()",
        "ELBComplianceChecker().elb_one()"]

class AWSResourceTaggingStandard:
    def __init__(self) -> None:
        self.standard_list = ["ACMComplianceChecker().acm_three()",
        "AppSyncComplianceChecker().appsync_four()",
        "AthenaComplianceChecker().athena_two()",
        "AthenaComplianceChecker().athena_three()",
        "AutoScalingComplianceChecker().autoscaling_ten()",
        "BackupComplianceChecker().backup_two()",
        "BackupComplianceChecker().backup_three()",
        "BackupComplianceChecker().backup_four()",
        "BackupComplianceChecker().backup_five()",
        "CloudFormationComplianceChecker().cloudformation_two()",
        "CloudFrontComplianceChecker().cloudfront_fourteen()",
        "CloudTrailComplianceChecker().cloudtrail_nine()",
        "CodeArtifactComplianceChecker().codeartifact_one()",
        "DetectiveComplianceChecker().detective_one()",
        "DMSComplianceChecker().dms_two()",
        "DMSComplianceChecker().dms_three()",
        "DMSComplianceChecker().dms_four()",
        "DMSComplianceChecker().dms_five()",
        "DynamoDBComplianceChecker().dynamodb_five()",
        "EC2ComplianceChecker().ec2_thirtythree()",
        "EC2ComplianceChecker().ec2_thirtyfour()",
        "EC2ComplianceChecker().ec2_thirtyfive()",
        "EC2ComplianceChecker().ec2_thirtysix()",
        "EC2ComplianceChecker().ec2_thirtyseven()",
        "EC2ComplianceChecker().ec2_thirtyeight()",
        "EC2ComplianceChecker().ec2_thirtynine()",
        "EC2ComplianceChecker().ec2_forty()",
        "EC2ComplianceChecker().ec2_fortyone()",
        "EC2ComplianceChecker().ec2_fortytwo()",
        "EC2ComplianceChecker().ec2_fortythree()",
        "EC2ComplianceChecker().ec2_fortyfour()",
        "EC2ComplianceChecker().ec2_fortyfive()",
        "EC2ComplianceChecker().ec2_fortysix()",
        "EC2ComplianceChecker().ec2_fortyseven()",
        "EC2ComplianceChecker().ec2_fortyeight()",
        "EC2ComplianceChecker().ec2_fortynine()",
        "EC2ComplianceChecker().ec2_fifty()",
        "EC2ComplianceChecker().ec2_fiftytwo()",
        "ECRComplianceChecker().ecr_four()",
        "ECSComplianceChecker().ecs_thirteen()",
        "ECSComplianceChecker().ecs_fourteen()",
        "ECSComplianceChecker().ecs_fifteen()",
        "EFSComplianceChecker().efs_five()",
        "EKSComplianceChecker().eks_six()",
        "EKSComplianceChecker().eks_seven()"]

class ServiceManagedStandardAWSControlTower:
    def __init__(self) -> None:
        self.standard_list = ["AccountComplianceChecker().account_one()",
        "ACMComplianceChecker().acm_one()",
        "APIGatewayComplianceChecker().apigateway_one()",
        "APIGatewayComplianceChecker().apigateway_two()",
        "APIGatewayComplianceChecker().apigateway_three()",
        "APIGatewayComplianceChecker().apigateway_four()",
        "APIGatewayComplianceChecker().apigateway_five()",
        "APIGatewayComplianceChecker().apigateway_eight()",
        "APIGatewayComplianceChecker().apigateway_nine()",
        "AutoScalingComplianceChecker().autoscaling_one()",
        "AutoScalingComplianceChecker().autoscaling_two()",
        "AutoScalingComplianceChecker().autoscaling_three()",
        "AutoScalingComplianceChecker().autoscaling_five()",
        "AutoScalingComplianceChecker().autoscaling_six()",
        "AutoScalingComplianceChecker().autoscaling_nine()",
        "CloudTrailComplianceChecker().cloudtrail_one()",
        "CloudTrailComplianceChecker().cloudtrail_two()",
        "CloudTrailComplianceChecker().cloudtrail_four()",
        "CloudTrailComplianceChecker().cloudtrail_five()",
        "CodeBuildComplianceChecker().codebuild_one()",
        "CodeBuildComplianceChecker().codebuild_two()",
        "CodeBuildComplianceChecker().codebuild_three()",
        "CodeBuildComplianceChecker().codebuild_four()",
        "DMSComplianceChecker().dms_one()",
        "DocumentDBComplianceChecker().docdb_one()",
        "DocumentDBComplianceChecker().docdb_two()",
        "DynamoDBComplianceChecker().dynamodb_one()",
        "DynamoDBComplianceChecker().dynamodb_two()",
        "EC2ComplianceChecker().ec2_one()",
        "EC2ComplianceChecker().ec2_two()",
        "EC2ComplianceChecker().ec2_three()",
        "EC2ComplianceChecker().ec2_four()",
        "EC2ComplianceChecker().ec2_six()",
        "EC2ComplianceChecker().ec2_seven()",
        "EC2ComplianceChecker().ec2_eight()",
        "EC2ComplianceChecker().ec2_nine()",
        "EC2ComplianceChecker().ec2_ten()",
        "EC2ComplianceChecker().ec2_fifteen()",
        "EC2ComplianceChecker().ec2_sixteen()",
        "EC2ComplianceChecker().ec2_seventeen()",
        "EC2ComplianceChecker().ec2_eighteen()",
        "EC2ComplianceChecker().ec2_nineteen()",
        "EC2ComplianceChecker().ec2_twenty()",
        "EC2ComplianceChecker().ec2_twentyone()",
        "EC2ComplianceChecker().ec2_twentytwo()",
        "EC2ComplianceChecker().ec2_twentyfive()",
        "ECRComplianceChecker().ecr_one()",
        "ECRComplianceChecker().ecr_two()",
        "ECRComplianceChecker().ecr_three()",
        "ECSComplianceChecker().ecs_one()",
        "ECSComplianceChecker().ecs_two()",
        "ECSComplianceChecker().ecs_three()",
        "ECSComplianceChecker().ecs_four()",
        "ECSComplianceChecker().ecs_five()",
        "ECSComplianceChecker().ecs_eight()",
        "ECSComplianceChecker().ecs_ten()",
        "ECSComplianceChecker().ecs_twelve()",
        "EFSComplianceChecker().efs_one()",
        "EFSComplianceChecker().efs_two()",
        "EFSComplianceChecker().efs_three()",
        "EFSComplianceChecker().efs_four()",
        "EKSComplianceChecker().eks_one()",
        "ElasticBeanstalkComplianceChecker().elasticbeanstalk_one()",
        "ElasticBeanstalkComplianceChecker().elasticbeanstalk_two()",
        "ELBComplianceChecker().elb_one()",
        "ELBComplianceChecker().elb_two()",
        "ELBComplianceChecker().elb_three()",
        "ELBComplianceChecker().elb_four()",
        "ELBComplianceChecker().elb_five()",
        "ELBComplianceChecker().elb_six()",
        "ELBComplianceChecker().elb_seven()",
        "ELBComplianceChecker().elb_eight()",
        "ELBComplianceChecker().elb_nine()",
        "ELBComplianceChecker().elb_ten()",
        "ELBComplianceChecker().elb_twelve()",
        "ELBComplianceChecker().elb_thirteen()",
        "ELBComplianceChecker().elb_fourteen()",
        "EMRComplianceChecker().emr_one()"]

class AllAWSSecurityHubControl:
    def __init__(self) -> None:
        self.standard_list = [
        "AccountComplianceChecker().account_one()",
        "AccountComplianceChecker().account_two()",
        # "ACMComplianceChecker().acm_one()",
        # "ACMComplianceChecker().acm_two()",
        # "ACMComplianceChecker().acm_three()",
        # "APIGatewayComplianceChecker().apigateway_one()",
        # "APIGatewayComplianceChecker().apigateway_two()",
        # "APIGatewayComplianceChecker().apigateway_three()",
        # "APIGatewayComplianceChecker().apigateway_four()",
        # "APIGatewayComplianceChecker().apigateway_five()",
        # "APIGatewayComplianceChecker().apigateway_eight()",
        # "APIGatewayComplianceChecker().apigateway_nine()",
        # "AppSyncComplianceChecker().appsync_two()",
        # "AppSyncComplianceChecker().appsync_four()",
        # "AppSyncComplianceChecker().appsync_five()",
        # "AthenaComplianceChecker().athena_two()",
        # "AthenaComplianceChecker().athena_three()",
        # "AthenaComplianceChecker().athena_four()",
        # "AutoScalingComplianceChecker().autoscaling_one()",
        # "AutoScalingComplianceChecker().autoscaling_two()",
        # "AutoScalingComplianceChecker().autoscaling_three()",
        # "AutoScalingComplianceChecker().autoscaling_five()",
        # "AutoScalingComplianceChecker().autoscaling_six()",
        # "AutoScalingComplianceChecker().autoscaling_nine()",
        # "AutoScalingComplianceChecker().autoscaling_ten()",
        # "BackupComplianceChecker().backup_one()",
        # "BackupComplianceChecker().backup_two()",
        # "BackupComplianceChecker().backup_three()",
        # "BackupComplianceChecker().backup_four()",
        # "BackupComplianceChecker().backup_five()",
        # "CloudFormationComplianceChecker().cloudformation_two()",
        # "CloudFrontComplianceChecker().cloudfront_one()",
        # "CloudFrontComplianceChecker().cloudfront_three()",
        # "CloudFrontComplianceChecker().cloudfront_four()",
        # "CloudFrontComplianceChecker().cloudfront_five()",
        # "CloudFrontComplianceChecker().cloudfront_six()",
        # "CloudFrontComplianceChecker().cloudfront_seven()",
        # "CloudFrontComplianceChecker().cloudfront_eight()",
        # "CloudFrontComplianceChecker().cloudfront_nine()",
        # "CloudFrontComplianceChecker().cloudfront_ten()",
        # "CloudFrontComplianceChecker().cloudfront_twelve()",
        # "CloudFrontComplianceChecker().cloudfront_thirteen()",
        # "CloudFrontComplianceChecker().cloudfront_fourteen()",
        # "CloudTrailComplianceChecker().cloudtrail_one()",
        # "CloudTrailComplianceChecker().cloudtrail_two()",
        # "CloudTrailComplianceChecker().cloudtrail_three()",
        # "CloudTrailComplianceChecker().cloudtrail_four()",
        # "CloudTrailComplianceChecker().cloudtrail_five()",
        # "CloudTrailComplianceChecker().cloudtrail_six()",
        # "CloudTrailComplianceChecker().cloudtrail_seven()",
        # "CloudTrailComplianceChecker().cloudtrail_nine()",
        # "CloudWatchComplianceChecker().cloudwatch_one()",
        # "CloudWatchComplianceChecker().cloudwatch_two()",
        # "CloudWatchComplianceChecker().cloudwatch_three()",
        # "CloudWatchComplianceChecker().cloudwatch_four()",
        # "CloudWatchComplianceChecker().cloudwatch_five()",
        # "CloudWatchComplianceChecker().cloudwatch_six()",
        # "CloudWatchComplianceChecker().cloudwatch_seven()",
        # "CloudWatchComplianceChecker().cloudwatch_eight()",
        # "CloudWatchComplianceChecker().cloudwatch_nine()",
        # "CloudWatchComplianceChecker().cloudwatch_ten()",
        # "CloudWatchComplianceChecker().cloudwatch_eleven()",
        # "CloudWatchComplianceChecker().cloudwatch_twelve()",
        # "CloudWatchComplianceChecker().cloudwatch_thirteen()",
        # "CloudWatchComplianceChecker().cloudwatch_fourteen()",
        # "CloudWatchComplianceChecker().cloudwatch_fifteen()",
        # "CloudWatchComplianceChecker().cloudwatch_sixteen()",
        # "CloudWatchComplianceChecker().cloudwatch_seventeen()",
        # "CodeArtifactComplianceChecker().codeartifact_one()",
        # "CodeBuildComplianceChecker().codebuild_one()",
        # "CodeBuildComplianceChecker().codebuild_two()",
        # "CodeBuildComplianceChecker().codebuild_three()",
        # "CodeBuildComplianceChecker().codebuild_four()",
        # "ConfigComplianceChecker().config_one()",
        # "DataFirehoseComplianceChecker().datafirehose_one()",
        # "DetectiveComplianceChecker().detective_one()",
        # "DMSComplianceChecker().dms_one()",
        # "DMSComplianceChecker().dms_two()",
        # "DMSComplianceChecker().dms_three()",
        # "DMSComplianceChecker().dms_four()",
        # "DMSComplianceChecker().dms_five()",
        # "DMSComplianceChecker().dms_six()",
        # "DMSComplianceChecker().dms_seven()",
        # "DMSComplianceChecker().dms_eight()",
        # "DMSComplianceChecker().dms_nine()",
        # "DMSComplianceChecker().dms_ten()",
        # "DMSComplianceChecker().dms_eleven()",
        # "DMSComplianceChecker().dms_twelve()",
        # "DocumentDBComplianceChecker().docdb_one()",
        # "DocumentDBComplianceChecker().docdb_two()",
        # "DocumentDBComplianceChecker().docdb_three()",
        # "DocumentDBComplianceChecker().docdb_four()",
        # "DocumentDBComplianceChecker().docdb_five()",
        # "DynamoDBComplianceChecker().dynamodb_one()",
        # "DynamoDBComplianceChecker().dynamodb_two()",
        # "DynamoDBComplianceChecker().dynamodb_three()",
        # "DynamoDBComplianceChecker().dynamodb_four()",
        # "DynamoDBComplianceChecker().dynamodb_five()",
        # "DynamoDBComplianceChecker().dynamodb_six()",
        # "DynamoDBComplianceChecker().dynamodb_seven()",
        # "EC2ComplianceChecker().ec2_one()",
        # "EC2ComplianceChecker().ec2_two()",
        # "EC2ComplianceChecker().ec2_three()",
        # "EC2ComplianceChecker().ec2_four()",
        # "EC2ComplianceChecker().ec2_six()",
        # "EC2ComplianceChecker().ec2_seven()",
        # "EC2ComplianceChecker().ec2_eight()",
        # "EC2ComplianceChecker().ec2_nine()",
        # "EC2ComplianceChecker().ec2_ten()",
        # "EC2ComplianceChecker().ec2_twelve()",
        # "EC2ComplianceChecker().ec2_thirteen()",
        # "EC2ComplianceChecker().ec2_fourteen()",
        # "EC2ComplianceChecker().ec2_fifteen()",
        # "EC2ComplianceChecker().ec2_sixteen()",
        # "EC2ComplianceChecker().ec2_seventeen()",
        # "EC2ComplianceChecker().ec2_eighteen()",
        # "EC2ComplianceChecker().ec2_nineteen()",
        # "EC2ComplianceChecker().ec2_twenty()",
        # "EC2ComplianceChecker().ec2_twentyone()",
        # "EC2ComplianceChecker().ec2_twentytwo()",
        # "EC2ComplianceChecker().ec2_twentythree()",
        # "EC2ComplianceChecker().ec2_twentyfour()",
        # "EC2ComplianceChecker().ec2_twentyfive()",
        # "EC2ComplianceChecker().ec2_thirtythree()",
        # "EC2ComplianceChecker().ec2_thirtyfour()",
        # "EC2ComplianceChecker().ec2_thirtyfive()",
        # "EC2ComplianceChecker().ec2_thirtysix()",
        # "EC2ComplianceChecker().ec2_thirtyseven()",
        # "EC2ComplianceChecker().ec2_thirtyeight()",
        # "EC2ComplianceChecker().ec2_thirtynine()",
        # "EC2ComplianceChecker().ec2_forty()",
        # "EC2ComplianceChecker().ec2_fortyone()",
        # "EC2ComplianceChecker().ec2_fortytwo()",
        # "EC2ComplianceChecker().ec2_fortythree()",
        # "EC2ComplianceChecker().ec2_fortyfour()",
        # "EC2ComplianceChecker().ec2_fortyfive()",
        # "EC2ComplianceChecker().ec2_fortysix()",
        # "EC2ComplianceChecker().ec2_fortyseven()",
        # "EC2ComplianceChecker().ec2_fortyeight()",
        # "EC2ComplianceChecker().ec2_fortynine()",
        # "EC2ComplianceChecker().ec2_fifty()",
        # "EC2ComplianceChecker().ec2_fiftyone()",
        # "EC2ComplianceChecker().ec2_fiftytwo()",
        # "EC2ComplianceChecker().ec2_fiftythree()",
        # "EC2ComplianceChecker().ec2_fiftyfour()"
        # "ECRComplianceChecker().ecr_one()",
        # "ECRComplianceChecker().ecr_two()",
        # "ECRComplianceChecker().ecr_three()",
        # "ECRComplianceChecker().ecr_four()",
        # "ECSComplianceChecker().ecs_one()",
        # "ECSComplianceChecker().ecs_two()",
        # "ECSComplianceChecker().ecs_three()",
        # "ECSComplianceChecker().ecs_four()",
        # "ECSComplianceChecker().ecs_five()",
        # "ECSComplianceChecker().ecs_eight()",
        # "ECSComplianceChecker().ecs_nine()",
        # "ECSComplianceChecker().ecs_ten()",
        # "ECSComplianceChecker().ecs_twelve()",
        # "ECSComplianceChecker().ecs_thirteen()",
        # "ECSComplianceChecker().ecs_fourteen()",
        # "ECSComplianceChecker().ecs_fifteen()",
        # "EFSComplianceChecker().efs_one()",
        # "EFSComplianceChecker().efs_two()",
        # "EFSComplianceChecker().efs_three()",
        # "EFSComplianceChecker().efs_four()",
        # "EFSComplianceChecker().efs_five()",
        # "EFSComplianceChecker().efs_six()",
        # "EKSComplianceChecker().eks_one()",
        # "EKSComplianceChecker().eks_two()",
        # "EKSComplianceChecker().eks_three()",
        # "EKSComplianceChecker().eks_six()",
        # "EKSComplianceChecker().eks_seven()",
        # "EKSComplianceChecker().eks_eight()",
        # "ElastiCacheComplianceChecker().elasticache_one()",
        # "ElastiCacheComplianceChecker().elasticache_two()",
        # "ElastiCacheComplianceChecker().elasticache_three()",
        # "ElastiCacheComplianceChecker().elasticache_four()",
        # "ElastiCacheComplianceChecker().elasticache_five()",
        # "ElastiCacheComplianceChecker().elasticache_six()",
        # "ElastiCacheComplianceChecker().elasticache_seven()",
        # "ElasticBeanstalkComplianceChecker().elasticbeanstalk_one()",
        # "ElasticBeanstalkComplianceChecker().elasticbeanstalk_two()",
        # "ElasticBeanstalkComplianceChecker().elasticbeanstalk_three()",
        # "ELBComplianceChecker().elb_one()",
        # "ELBComplianceChecker().elb_two()",
        # "ELBComplianceChecker().elb_three()",
        # "ELBComplianceChecker().elb_four()",
        # "ELBComplianceChecker().elb_five()",
        # "ELBComplianceChecker().elb_six()",
        # "ELBComplianceChecker().elb_seven()",
        # "ELBComplianceChecker().elb_eight()",
        # "ELBComplianceChecker().elb_nine()",
        # "ELBComplianceChecker().elb_ten()",
        # "ELBComplianceChecker().elb_twelve()",
        # "ELBComplianceChecker().elb_thirteen()",
        # "ELBComplianceChecker().elb_fourteen()",
        # "ELBComplianceChecker().elb_sixteen()",
        # "EMRComplianceChecker().emr_one()",
        # "EMRComplianceChecker().emr_two()",
        # "ESComplianceChecker().es_one()",
        # "ESComplianceChecker().es_two()",
        # "ESComplianceChecker().es_three()",
        # "ESComplianceChecker().es_four()",
        # "ESComplianceChecker().es_five()",
        # "ESComplianceChecker().es_six()",
        # "ESComplianceChecker().es_seven()",
        # "ESComplianceChecker().es_eight()",
        # "ESComplianceChecker().es_nine()",
        # "EventBridgeComplianceChecker().eventbridge_two()",
        # "EventBridgeComplianceChecker().eventbridge_three()",
        # "EventBridgeComplianceChecker().eventbridge_four()",
        # "FSxComplianceChecker().fsx_one()",
        # "FSxComplianceChecker().fsx_two()",
        # "GlobalAcceleratorComplianceChecker().globalaccelerator_one()",
        # "GlueComplianceChecker().glue_one()",
        # "GuardDutyComplianceChecker().guardduty_one()",
        # "GuardDutyComplianceChecker().guardduty_two()",
        # "GuardDutyComplianceChecker().guardduty_three()",
        # "GuardDutyComplianceChecker().guardduty_four()",
        # "IAMComplianceChecker().iam_one()",
        # "IAMComplianceChecker().iam_two()",
        # "IAMComplianceChecker().iam_three()",
        # "IAMComplianceChecker().iam_four()",
        # "IAMComplianceChecker().iam_five()",
        # "IAMComplianceChecker().iam_six()",
        # "IAMComplianceChecker().iam_seven()",
        # "IAMComplianceChecker().iam_eight()",
        # "IAMComplianceChecker().iam_nine()",
        # "IAMComplianceChecker().iam_ten()",
        # "IAMComplianceChecker().iam_eleven()",
        # "IAMComplianceChecker().iam_twelve()",
        # "IAMComplianceChecker().iam_thirteen()",
        # "IAMComplianceChecker().iam_fourteen()",
        # "IAMComplianceChecker().iam_fifteen()",
        # "IAMComplianceChecker().iam_sixteen()",
        # "IAMComplianceChecker().iam_seventeen()",
        # "IAMComplianceChecker().iam_eighteen()",
        # "IAMComplianceChecker().iam_nineteen()",
        # "IAMComplianceChecker().iam_twentyone()",
        # "IAMComplianceChecker().iam_twentytwo()",
        # "IAMComplianceChecker().iam_twentythree()",
        # "IAMComplianceChecker().iam_twentyfour()",
        # "IAMComplianceChecker().iam_twentyfive()",
        # "IAMComplianceChecker().iam_twentysix()",
        # "IAMComplianceChecker().iam_twentyseven()",
        # "IAMComplianceChecker().iam_twentyeight()",
        # "IoTComplianceChecker().iot_one()",
        # "IoTComplianceChecker().iot_two()",
        # "IoTComplianceChecker().iot_three()",
        # "IoTComplianceChecker().iot_four()",
        # "IoTComplianceChecker().iot_five()",
        # "IoTComplianceChecker().iot_six()",
        # "KinesisComplianceChecker().kinesis_one()",
        # "KinesisComplianceChecker().kinesis_two()",
        # "KMSComplianceChecker().kms_one()",
        # "KMSComplianceChecker().kms_two()",
        # "KMSComplianceChecker().kms_three()",
        # "KMSComplianceChecker().kms_four()",
        # "LambdaComplianceChecker().lambda_one()",
        # "LambdaComplianceChecker().lambda_two()",
        # "LambdaComplianceChecker().lambda_three()",
        # "LambdaComplianceChecker().lambda_five()",
        # "LambdaComplianceChecker().lambda_six()",
        # "MacieComplianceChecker().macie_one()",
        # "MacieComplianceChecker().macie_two()",
        # "MSKComplianceChecker().msk_one()",
        # "MSKComplianceChecker().msk_two()",
        # "MQComplianceChecker().mq_two()",
        # "MQComplianceChecker().mq_three()",
        # "MQComplianceChecker().mq_four()",
        # "MQComplianceChecker().mq_five()",
        # "MQComplianceChecker().mq_six()",
        # "NeptuneComplianceChecker().neptune_one()",
        # "NeptuneComplianceChecker().neptune_two()",
        # "NeptuneComplianceChecker().neptune_three()",
        # "NeptuneComplianceChecker().neptune_four()",
        # "NeptuneComplianceChecker().neptune_five()",
        # "NeptuneComplianceChecker().neptune_six()",
        # "NeptuneComplianceChecker().neptune_seven()",
        # "NeptuneComplianceChecker().neptune_eight()",
        # "NeptuneComplianceChecker().neptune_nine()",
        # "NetworkFirewallComplianceChecker().networkfirewall_one()",
        # "NetworkFirewallComplianceChecker().networkfirewall_two()",
        # "NetworkFirewallComplianceChecker().networkfirewall_three()",
        # "NetworkFirewallComplianceChecker().networkfirewall_four()",
        # "NetworkFirewallComplianceChecker().networkfirewall_five()",
        # "NetworkFirewallComplianceChecker().networkfirewall_six()",
        # "NetworkFirewallComplianceChecker().networkfirewall_seven()",
        # "NetworkFirewallComplianceChecker().networkfirewall_eight()",
        # "NetworkFirewallComplianceChecker().networkfirewall_nine()",
        # "OpensearchComplianceChecker().opensearch_one()",
        # "OpensearchComplianceChecker().opensearch_two()",
        # "OpensearchComplianceChecker().opensearch_three()",
        # "OpensearchComplianceChecker().opensearch_four()",
        # "OpensearchComplianceChecker().opensearch_five()",
        # "OpensearchComplianceChecker().opensearch_six()",
        # "OpensearchComplianceChecker().opensearch_seven()",
        # "OpensearchComplianceChecker().opensearch_eight()",
        # "OpensearchComplianceChecker().opensearch_nine()",
        # "OpensearchComplianceChecker().opensearch_ten()",
        # "OpensearchComplianceChecker().opensearch_eleven()",
        # "PCAComplianceChecker().pca_one()",
        # "RDSComplianceChecker().rds_one()",
        # "RDSComplianceChecker().rds_two()",
        # "RDSComplianceChecker().rds_three()",
        # "RDSComplianceChecker().rds_four()",
        # "RDSComplianceChecker().rds_five()",
        # "RDSComplianceChecker().rds_six()",
        # "RDSComplianceChecker().rds_seven()",
        # "RDSComplianceChecker().rds_eight()",
        # "RDSComplianceChecker().rds_nine()",
        # "RDSComplianceChecker().rds_ten()",
        # "RDSComplianceChecker().rds_eleven()",
        # "RDSComplianceChecker().rds_twelve()",
        # "RDSComplianceChecker().rds_thirteen()",
        # "RDSComplianceChecker().rds_fourteen()",
        # "RDSComplianceChecker().rds_fifteen()",
        # "RDSComplianceChecker().rds_sixteen()",
        # "RDSComplianceChecker().rds_seventeen()",
        ]